spring:
  datasource:
    url: jdbc:mysql://192.168.43.86:3306/docker?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
      #1.配置mysql连接
    #schema:
    # - classpath*:sql/*.sql
    #initialization-mode: always
    #2.自动添加sql表，添加完成需要注释掉，不然会重复建表