spring:
  redis:
    #缓存配置
    redis:
      # Redis服务器地址
      host: 192.168.43.86
      # Redis服务器连接端口
      port: 6379
      # Redis数据库索引（默认为0）
      database: 0
      # 连接超时时间（毫秒）
      timeout: 1000
      jedis:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 20
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 10
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.43.86:3306/docker?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC