spring:
  servlet:
    multipart:
      enabled: true #启动servlet上传
      max-file-size:  10MB #设置支持单个文件上传大小限制
      max-request-size: 20MB #设置总体大小请求 or 设置最大的请求文件大小
      file-size-threshold: 512KB #当上传文件达到指定配置量的时候，将文件内容写入磁盘
      location: / # 设置上传的临时目录